### ISSUE TITLE
ImportBotAuthorizationRequest Failure

### ISSUE THREAD

**Issue by Aparna-Subbaraya** [jimiljojo/visa-slot-bot#1]
Hi, 
I'm seeing the following error:
mycomputer:visa-slot-bot user$ python3 tele_visa_script.py
Please enter your phone (or bot token): <10digitappid>:<apphash>
Traceback (most recent call last):
  File "/Users/apsubbar/Downloads/visa_slot/visa-slot-bot/tele_visa_script.py", line 23, in <module>
    client.start()
  File "/usr/local/lib/python3.9/site-packages/telethon/client/auth.py", line 133, in start
    else self.loop.run_until_complete(coro)
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/telethon/client/auth.py", line 182, in _start
    await self.sign_in(bot_token=bot_token)
  File "/usr/local/lib/python3.9/site-packages/telethon/client/auth.py", line 368, in sign_in
    result = await self(request)
  File "/usr/local/lib/python3.9/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/usr/local/lib/python3.9/site-packages/telethon/client/users.py", line 79, in _call
    result = await future
telethon.errors.rpcerrorlist.ApiIdInvalidError: The api_id/api_hash combination is invalid (caused by ImportBotAuthorizationRequest)

I tried by creating 2 different bots. Have verified that appid:hash is inserted correctly in the .py file as well as copied correctly while initiating script run.

Have you seen this before?

RUNNING Python 3.9.1

**Comment by jimiljojo** [comment]
hi @Aparna-Subbaraya - i added new instructions on auth. can you try following that and updating your API ID and hash?

**Comment by Aparna-Subbaraya** [comment]
Thanks @jimiljojo, that helped with the auth failure!
